name: Run WebDriverIO Tests on AWS Device Farm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # specify your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
      - name: Zip and Push
        
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AWS.SECRET.KEY }}
          aws-secret-access-key: ${{ AWS.SECRET.ACCESS.KEY }}
          aws-region: us-west-2

      # configure Device Pool
      - name: List device pools
        uses: realm/aws-devicefarm/list-device-pools@v1
        id: list-device-pools
        with:
          project_arn: ${{ secrets.AWS_PROJECT_ARN }}
